services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: notes_backend
    ports:
      - '5100:5100'
    env_file:
      - backend/.env
    depends_on:
      - postgres
    networks:
      - notes-network
    environment:
      DATABASE_URL: postgresql://notes:notes@postgres:5432/notes
  postgres:
    image: postgres:16
    container_name: notes_postgres
    volumes:
      - ~/.db_data/notes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - '5432:5432'
    restart: 'no'
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
