version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: dockerimage/Dockerfile
    container_name: ciphernotes_app
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ciphernotes_data:/data
    restart: unless-stopped

volumes:
  ciphernotes_data:
